apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-price-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: car-price-app
  template:
    metadata:
      labels:
        app: car-price-app
    spec:
      containers:
        - name: car-price-container
          image: mrblake65/car-price-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: car-price-app-service
spec:
  selector:
    app: car-price-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
